### ISSUE TITLE
节点ID没有正确设置

### ISSUE THREAD

**Issue by Colinwood11** [SuicidalCat/Airport-toolkit#1]
使用一键安装后，节点ID没有正确设置（会为0），需要手动进入/soft/shadowsocks中的 userapiconfig.py 手动修改ID

系统为C7

安装使用的是WEBAPI 
BLABLALBA

**Comment by SuicidalCat** [comment]
這個問題已經重現，稍後進行fix

**Comment by SuicidalCat** [comment]
已經修復
